### ISSUE TITLE
List of API's to implement (Album and Photos)

### ISSUE THREAD

**Issue by sudeepgaddam** [RayZ-O/distributed_system#10]
1. URL/albums?id=1 => Gives metadata about this album
2. URL/photos/albums?id=1  => returns link to all photos in this album with id 1.
3. URL/albums/person?id=1 => Returns metadata of all the albums uploaded by user with id =1

Can you please correct? Also, Can you keep adding more URL's so that we both are on same page.

**Comment by RayZ-O** [comment]
I've finished User API specification

**Comment by RayZ-O** [comment]
Moved to new repository
